### ISSUE TITLE
Restrict bind address to localhost only.

### ISSUE THREAD

**Issue by braincomb** [strongloop/strong-pm#155]
As it is right now, StrongLoop Process Manager listens globally, meaning it can be accessed from outside. Having an extra port open outside is a security concern. Yes, we can HTTP AUTH it but it's not the same. We should be able to restrict to localhost only without mingling with firewall rules.

**Comment by rmg** [comment]
@sam-github @chandadharap @kraman this doesn't fit with the whole mesh/orchestration concept, but it's very valid for a single server scenario. Especially since you can use ssh tunnelling to access localhost bound ports.

@sam-github what do you think about `--listen` accepting an address:port format? Should be backwards compatible, and the option is `--listen` not `--port`, so the name still makes sense.

**Comment by kraman** [comment]
@rmg Arc PM view (and backend) would need to allow connecting over SSH tunnel. We will need to make sure web-sockets (for notifications/updates) continue to work in that case.

**Comment by rmg** [comment]
@kraman I would expect the http port to still be exposed for that use case. I think if you're specifically binding pm to localhost you're doing so intentionally with the expectation that it is no longer remotely accessible. The fact that `http+ssh://` works is more of a convenience so you don't need to start up a remote shell for _every_ operation you perform on the server.

**Comment by ritch** [comment]
> --listen accepting an address:port format?

+1 for this... why not just make it configurable and use node's default OOTB?

**Comment by rmg** [comment]
@ritch that's what the feature request is. It already listens on the default (`0.0.0.0`).
