### ISSUE TITLE
windows issues : Cannot deploy app from windows to remote linux pm server

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-pm#166]
Connect to strongloop-internal/scrum-nodeops#389

$ slc pm -l 7777
slc pm: StrongLoop PM v3.1.15 (API v5.0.9) listening on port `7777`
slc pm: control listening on path `/root/pmctl`
slc pm: listen on 7777, work base is `/root/.strong-pm`
Stop current (none)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
  at errnoException (child_process.js:1011:11)
  at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by piscisaureus** [comment]
@sam-github

I noticed that there are a couple of places where we use npm. Would it make sense to create a separate 'spawn-npm' package that just does the right thing(tm).

The other thing is that ideally we wouldn't run npm via the .cmd shim. Instead it'd be more ideal to locate npm-cli.js and run it directly. Would it be an idea to make npm a dependency of strongloop so we always know where it is? Or would that break in terrible ways?

**Comment by chandadharap** [comment]
Connect to strongloop-internal/scrum-nodeops#389

**Comment by sam-github** [comment]
Having an npm-spawn could make sense. `slc build` and strong-pm are, I think, the only callers of npm ATM.

What's wrong with calling via .cmd shim?

It would be possible to find npm.cmd in the path, read the shim, find the npm-cli.js location, and direct run the npm-cli.js... That might be too convoluted to do just as an effort to reduce install time.

npm would have to be a dependency of strong-build and strong-pm, and then we face the possibility that its not the same version as your node's npm.

npm is a pretty HUGE dependency :-( I've really wanted to avoid depending on it, strongloop is huge enough as it is. If I can avoid by just adding a `cmd /c/s` before the spawn command, it seems pretty straight-forward to do.

But maybe that is quixotic, and I should just make it a dependency.

**Comment by rmg** [comment]
13MB for npm is pretty small compared to the 380MB that `npm install -g strongloop` is already.

**Comment by piscisaureus** [comment]
@sam-github 

> What's wrong with calling via .cmd shim?

Currently, not so much. But .cmd files have this problem that they can't be used to reliably forward command line arguments. That's because certain characters (`%` and `^` and `!`) have to be escaped. But since the .cmd processor re-interprets them they'd have to double escaped, or (if the .cmd file calls another .cmd file) quadruple-escaped, etc.

> 13MB for npm is pretty small compared to the 380MB that npm install -g strongloop is already.

Agreed, although we'd have to be a bit smarter, because as it's structured now there'd probably be 5 copies (or so) in strongloop.

**Comment by sam-github** [comment]
@cgole

I deployed from a Windows VM on mac (win 7, node 0.12.7) to its Mac host pm, and to a remote linux laptop, both worked fine.

I suspect that either `npm` was not in the path for the `root` user (you are in /root, I assume you are `root`) on Linux, or that perhaps pm was incompletely installed, and failed to find `sl-run.js` in order to run it.

I don't see how pm could even notice whether or not the remote HTTP API client was or was not on Windows, but life is surprising.

Can you reproduce?

**Comment by cgole** [comment]
worked.
