### ISSUE TITLE
How to setting the access log  file of my deployed app  ?

### ISSUE THREAD

**Issue by toplinuxsir** [strongloop/strong-pm#296]
If I deployed an app in strong-pm , I want to store the access log into the specified  file , just like nginx's access log in /var/log/nginx/access.log 

How to ?
Thanks !

**Comment by rmg** [comment]
Unfortunately, strong-pm does not currently support this. All logs from strong-pm and apps deployed to it are combined.

What level of customization are you looking for?

**Comment by toplinuxsir** [comment]
Save the HTTP access log  and error log (such as exceptions raised by strongloop  )

**Comment by rmg** [comment]
@toplinuxsir do you mean strong-pm's access and errors? Or the deployed applications' access and error logs?

Since strong-pm itself has not visibility into http access and errors of the app, or even whether it is http based, I think the best we could do for this scenario is log the application's stdout and stderr to separate files and document this as an option for simple log differentiation.

**Comment by toplinuxsir** [comment]
@rmg  It's the  The deployed application's access and error logs 
It's better to support log file rotate

**Comment by sam-github** [comment]
@toplinuxsir strong-pm doesn't log access logs, use a tool like https://github.com/expressjs/morgan to write HTTP access logs.

**Comment by toplinuxsir** [comment]
@Sam Roberts
I got it , Thanks !

2015-12-09 6:31 GMT+08:00 Sam Roberts <notifications@github.com>:
