### ISSUE TITLE
Permission error when deploy app

### ISSUE THREAD

**Issue by Lunigorn** [strongloop/strong-pm#317]
I get app from [here](http://strong-pm.io/getting-started/#start),
then make docker container like [here](http://strong-pm.io/prod/#docker),
then deploy app like [here](http://strong-pm.io/prod/#deploy).

then I get error:

```
Untar /tmp/strong-pm-1-1455648088693/application.tgz failed with: Error: EACCES, open '/home/strong-pm/svc/1/work/d627305e429a0e04810d241d3a136170c15a948d.1455648088724/.eslintignore'
Failed to deploy `..\express-example-app-1.0.2.tgz` as `express-example-app` to `http://192.168.1.36:8701/` via `http://192.168.1.36:8701/`
```

How to solve this problem?

**Comment by cleever** [comment]
Same here.

**Comment by gggin** [comment]
Same here

**Comment by rmg** [comment]
@cleever @gggin are you both also deploying from Windows, Docker, and using a tarball created by `slc build`?

**Comment by cleever** [comment]
@rmg. Yes. First of all, I ran 'slc build', to create a tar.gz file.

(Windows Enviroment to Ubuntu)

**Comment by gggin** [comment]
Windows Enviroment to Ubuntu same
no docker!
I'm a beginner I just use GUI(web page)

**Comment by XiaochenLi1984** [comment]
win -> ubuntu, not docker. Application.tgz built by slc build or arc gui.

**Comment by rmg** [comment]
Can you also all give the output of `slc version` on your workstations?

And the output from `sl-pm --version` (or `slc version`) on your servers?

**Comment by gggin** [comment]
![image](https://cloud.githubusercontent.com/assets/3293064/13273100/f655232a-dadb-11e5-9cf7-54c1b1cfc8d1.png)

![image](https://cloud.githubusercontent.com/assets/3293064/13273129/272f33fa-dadc-11e5-8e44-bb618dedd3d5.png)

**Comment by XiaochenLi1984** [comment]
The reason is that application.tgz built on Win is not assigned a proper permission and fails to be extracted on Ubuntu. I've found a temporary solution. 

1. Go to path-to-npm/node_modules/strongloop/node_modules/strong-pack/index.js,  add a new option key to the pack() method like: 
![image](https://cloud.githubusercontent.com/assets/13462245/13311035/10f62e80-dbf0-11e5-9466-6eb2f0e11587.png)

This key is used when parsing the tar options.

2. Then go to path-to-npm/node_modules/strongloop/node_modules/tar-fs/index.js, find exports.pack method, and utilize the options we add in step 1 and assign a proper permission, as a linux convention, 744 for folders and 644 for files.
![image](https://cloud.githubusercontent.com/assets/13462245/13311123/c190507c-dbf0-11e5-8bda-d2af00ef3aa6.png)

Again this is only a temporary solution for deploying app from win to strong-pm running on Ubuntu.

**Comment by rmg** [comment]
Great sleuthing, @XiaochenLi1984!

**Comment by cleever** [comment]
Thanks @rmg and @XiaochenLi1984 !

**Comment by rmg** [comment]
@Lunigorn @gggin @cleever @XiaochenLi1984 sorry for the auto-close.

I've released strong-pack v1.0.1 which should fix this. It's a nested dependency of strong-build, so the best way to get it will be to run `npm install -g strongloop` on your Windows machines.

After that, `slc build` should work properly from Windows and allow you to deploy the generated tarballs to strong-pm.

@Lunigorn would you please close if this works for you or comment if it does not?

**Comment by XiaochenLi1984** [comment]
@rmg Thanks, it works on my Windows.

**Comment by Lunigorn** [comment]
@rmg Thanks, it works.

**Comment by gggin** [comment]
@rmg Thanks, so great!
