### ISSUE TITLE
ENOMEM takes down strong-pm in a way that upstart is not restarting it

### ISSUE THREAD

**Issue by despairblue** [strongloop/strong-pm#330]
We had a couple of graphics magick jobs running wild, so that the kernel eventually killed one of them. That somehow tear down the whole node server, including strong-pm, in a way that upstart never restarted it.

[Logs](https://gist.github.com/despairblue/1bf870bbeea58aaddbad):
* Strong-pm shut down at 16:50:19 and
* restarted (by issuing `sudo service strong-pm restart`) at 17:52:11.

I'm not completely familiar with the upstart script that strong-pm comes with, but shouldn't upstart restart a crashing daemon by default? Does anyone have an idea why upstart wouldn't do it? Is it possible that upstart was killed itself? This kind of baffles me :confused: 

I'd appreciate any help. Thanks in advance.

**Comment by sam-github** [comment]
cc: @rmg

**Comment by rmg** [comment]
Interesting... It looks like the strong-pm process itself may not have actually crashed.. It certainly lost the ability to respawn workers, though.

@despairblue for completeness, are you able to sanitize and attach `/etc/init/strong-pm.conf`? This appears to be running on Ubuntu 14.04 or newer. Can you confirm? The version of node would probably also be helpful for anyone attempting to reproduce this.

**Comment by despairblue** [comment]
@rmg Thanks for looking into this.

> This appears to be running on Ubuntu 14.04 or newer. Can you confirm?

Yeah
```
Linux backend-2 3.19.0-41-generic #46~14.04.2-Ubuntu SMP Tue Dec 8 17:46:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

> `/etc/init/strong-pm.conf`

Not sure what to sanitize in here, it does not seem to contain any secret information :confused: 
```
# strong-pm
# Generated by strong-service-upstart on 2016-01-12T22:49:36.991Z

description "StrongLoop Process Manager"
author "root"

# Start on boot/reboot
start on runlevel [2345]

# Stop on shutdown/reboot
stop on runlevel [016]

# To start/stop strong-pm service manually, run:
#
# /sbin/initctl start strong-pm
# /sbin/initctl stop strong-pm

respawn

# Log all service output to /var/log/strong-pm.log
# Log rotation is handled by Upstart
console log

# User & Group to run service as:
chdir /var/lib/strong-pm
setuid strong-pm
setgid strong-pm

# Arbitrarily high limit on number of open file descriptors:
limit nofile 50000 50000

# Enable core dumps:
limit core unlimited unlimited

# Environment variables:
env HOME=/var/lib/strong-pm


# Run our actual application
exec /usr/local/bin/node /usr/local/lib/node_modules/strong-pm/bin/sl-pm.js --listen 8701 --base /var/lib/strong-pm --base-port 3000 --driver direct
```

> The version of node

```sh
$ node --version
v5.6.0
```

**Comment by rmg** [comment]
@despairblue how much memory is there on this server? Is swap enabled?

**Comment by despairblue** [comment]
Not a lot. And no swap. I could enable swap, but that would probably just make the server unusably slow before the oom killer kills a process, instead of just killing it right away and thus giving the load balancer a chance to route the traffic to another server.

`free -m`

```sh
             total       used       free     shared    buffers     cached
Mem:          1676        894        781          0         44        273
-/+ buffers/cache:        576       1100
Swap:            0          0          0
```

**Comment by rmg** [comment]
Ideally each node process will have about 1-1.5GB of memory, and v8 itself caps the memory at around 1.5GB. If this application is the only thing running on this server, then adding 512mb of swap _might_ let the kernel swap out pages that it barely uses without impacting performance. This would work if your only barely running out of memory, of course.

The catch is that you are using GraphicsMagick. Assuming you are using [gm](http://aheckmann.github.com/gm/), then a new process is being spawned for each set of image manipulations, and the memory used for buffering the input, output, and performing the manipulations themselves would all depend on the size of the images. And of course doing multiple manipulations in parallel would further compound the issue.

#### Recommendation
Given how unpredictable systems become when the OOM killer goes hunting, you should probably consider throttling or increasing the amount of memory on these worker servers so that you can reduce the frequency of these events rather than relying entirely on the load balancer since recovery from running out of memory may end up requiring manual intervention.

**Comment by despairblue** [comment]
@rmg you're right. OOM is completely arbitrary. I wonder if the kernel could just initiate a reboot in that case.

Thanks for the help!
